### ISSUE TITLE
TypeError: a new-style class can't have only classic bases (Plone 5.2.2 and src/bda.plone.shop)

### ISSUE THREAD

**Issue by registroforzado** [bluedynamics/bda.plone.shop#121]
Is there a way to solve this? Thank you

$ bin/client1 fg
Traceback (most recent call last):
  File "bin/client1", line 309, in <module>
    import plone.recipe.zope2instance.ctl
  File "/home/plone/5/buildout-cache/eggs/plone.recipe.zope2instance-6.7.5-py2.7.egg/plone/__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    for dist in working_set
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3279, in <genexpr>
    for dist in working_set
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2783, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2767, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1432, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/home/plone/5/buildout-cache/eggs/odict-1.7.0-py2.7.egg/EGG-INFO/namespace_packages.txt'
$ bin/client1 fg
/home/plone/5/buildout-cache/eggs/Products.GenericSetup-2.0.2-py2.7.egg/Products/GenericSetup/registry.py:16: ImportWarning: Not importing directory '/home/plone/5/buildout-cache/eggs/Products.GenericSetup-2.0.2-py2.7.egg/Products/GenericSetup/xml': missing __init__.py
  from xml.sax import parseString
2020-10-18 02:32:23,917 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2020-10-18 02:32:23,924 WARNING [Init:89][MainThread] Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
/home/plone/5/buildout-cache/eggs/Products.CMFPlacefulWorkflow-2.0.2-py2.7.egg/Products/CMFPlacefulWorkflow/permissions.py:5: DeprecationWarning: setDefaultRoles is deprecated. Please use addPermission from AccessControl.Permission.
  from Products.CMFCore.permissions import setDefaultRoles
2020-10-18 02:32:24,433 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied sql_quote patch
2020-10-18 02:32:24,514 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied in_portal patch
2020-10-18 02:32:24,514 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied password_validation patch
2020-10-18 02:32:24,526 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied pac patch
/home/plone/5/buildout-cache/eggs/Products.PloneHotfix20200121-1.1-py2.7.egg/Products/PloneHotfix20200121/utils.py:4: DeprecationWarning: getSiteEncoding: `getSiteEncoding` is deprecated. Plone only supports UTF-8 currently. This method always returns "utf-8"
  from Products.CMFPlone.utils import *
2020-10-18 02:32:24,543 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied content patch
2020-10-18 02:32:24,547 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied layout patch
/home/plone/5/buildout-cache/eggs/PyJWT-1.7.1-py2.7.egg/jwt/utils.py:8: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.utils import (
2020-10-18 02:32:24,657 INFO    [Products.PloneHotfix20200121:49][MainThread] Applied restapi_local_roles patch
2020-10-18 02:32:24,657 INFO    [Products.PloneHotfix20200121:57][MainThread] Hotfix installed
/home/plone/5/buildout-cache/eggs/Products.PortalTransforms-3.1.8-py2.7.egg/Products/PortalTransforms/transforms/text_to_html.py:2: DeprecationWarning: html_quote is deprecated. Please import from DocumentTemplate.html_quote. These shims will go away in DocumentTemplate 4.0.
  from DocumentTemplate.DT_Util import html_quote
2020-10-18 02:32:24,819 INFO    [ZEO.ClientStorage:209][MainThread] zeostorage ClientStorage (pid=11297) created RW/normal for storage: '1'
2020-10-18 02:32:24,820 INFO    [ZEO.cache:208][MainThread] created temporary cache file '<fdopen>'
2020-10-18 02:32:24,828 INFO    [ZEO.asyncio.base:51][zeostorage zeo client networking thread] Connected Protocol((u'127.0.0.1', 8522), '1', False)
2020-10-18 02:32:24,829 INFO    [ZEO.ClientStorage:366][zeostorage zeo client networking thread] zeostorage Connected to storage: ('localhost.localdomain', 8522)
2020-10-18 02:32:24,832 WARNING [TemporaryStorage:93][MainThread] DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

/home/plone/5/buildout-cache/eggs/tempstorage-5.1-py2.7.egg/tempstorage/TemporaryStorage.py:94: DeprecationWarning: DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

  warnings.warn(deprecation_warning, DeprecationWarning)
2020-10-18 02:32:24,834 INFO    [ZEO.ClientStorage:209][MainThread] sitio_plone5 ClientStorage (pid=11297) created RW/normal for storage: 'sitio_plone5'
2020-10-18 02:32:24,834 INFO    [ZEO.cache:208][MainThread] created temporary cache file '<fdopen>'
2020-10-18 02:32:24,836 INFO    [ZEO.asyncio.base:51][sitio_plone5 zeo client networking thread] Connected Protocol((u'127.0.0.1', 8522), 'sitio_plone5', False)
2020-10-18 02:32:24,837 INFO    [ZEO.ClientStorage:366][sitio_plone5 zeo client networking thread] sitio_plone5 Connected to storage: ('localhost.localdomain', 8522)
2020-10-18 02:32:24,839 INFO    [ZEO.ClientStorage:209][MainThread] sitio_plone5tiendas ClientStorage (pid=11297) created RW/normal for storage: 'sitio_plone5tiendas'
2020-10-18 02:32:24,840 INFO    [ZEO.cache:208][MainThread] created temporary cache file '<fdopen>'
2020-10-18 02:32:24,841 INFO    [ZEO.asyncio.base:51][sitio_plone5tiendas zeo client networking thread] Connected Protocol((u'127.0.0.1', 8522), 'sitio_plone5tiendas', False)
2020-10-18 02:32:24,842 INFO    [ZEO.ClientStorage:366][sitio_plone5tiendas zeo client networking thread] sitio_plone5tiendas Connected to storage: ('localhost.localdomain', 8522)
2020-10-18 02:32:24,845 INFO    [ZEO.ClientStorage:209][MainThread] sitio_plone5lineage ClientStorage (pid=11297) created RW/normal for storage: 'sitio_plone5lineage'
2020-10-18 02:32:24,845 INFO    [ZEO.cache:208][MainThread] created temporary cache file '<fdopen>'
2020-10-18 02:32:24,846 INFO    [ZEO.asyncio.base:51][sitio_plone5lineage zeo client networking thread] Connected Protocol((u'127.0.0.1', 8522), 'sitio_plone5lineage', False)
2020-10-18 02:32:24,847 INFO    [ZEO.ClientStorage:366][sitio_plone5lineage zeo client networking thread] sitio_plone5lineage Connected to storage: ('localhost.localdomain', 8522)
Traceback (most recent call last):
  File "/home/plone/5/zeocluster/parts/client1/bin/interpreter", line 331, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/serve.py", line 255, in <module>
    sys.exit(main() or 0)
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/serve.py", line 190, in run
    global_conf=vars)
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/plone/5/buildout-cache/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/run.py", line 71, in make_wsgi_app
    starter.prepare()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/Startup/starter.py", line 99, in startZope
    Zope2.startup_wsgi()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/App/startup.py", line 143, in startup
    load_zcml()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/App/startup.py", line 58, in load_zcml
    load_site()
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/plone/5/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/OFS/metaconfigure.py", line 47, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 235, in _handle_exception
    reraise(exc, None, sys.exc_info()[2])
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/home/plone/5/buildout-cache/eggs/zope.configuration-4.4.0-py2.7.egg/zope/configuration/config.py", line 869, in finish
    actions = self.handler(context, **args)
  File "/home/plone/5/buildout-cache/eggs/z3c.autoinclude-0.4.0-py2.7.egg/z3c/autoinclude/zcml.py", line 119, in includePluginsDirective
    info = PluginFinder(dotted_name).includableInfo(zcml_to_look_for)
  File "/home/plone/5/buildout-cache/eggs/z3c.autoinclude-0.4.0-py2.7.egg/z3c/autoinclude/plugin.py", line 24, in includableInfo
    groups = zcml_to_include(plugin_dottedname, zcml_to_look_for)
  File "/home/plone/5/buildout-cache/eggs/z3c.autoinclude-0.4.0-py2.7.egg/z3c/autoinclude/plugin.py", line 52, in zcml_to_include
    filename = resource_filename(dotted_name, zcmlgroup)
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1144, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/home/plone/5/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 361, in get_provider
    __import__(moduleOrReq)
  File "/home/plone/5/zeocluster/src/bda.plone.shop/src/bda/plone/shop/__init__.py", line 3, in <module>
    from bda.plone.shop.user.properties import UserPropertiesPASPlugin
  File "/home/plone/5/zeocluster/src/bda.plone.shop/src/bda/plone/shop/user/properties.py", line 3, in <module>
    from bda.plone.checkout.vocabularies import get_pycountry_name
  File "/home/plone/5/zeocluster/src/bda.plone.checkout/src/bda/plone/checkout/vocabularies.py", line 19, in <module>
    (country.numeric, safe_unicode(_c(country.name))) for country in pycountry.countries
  File "/home/plone/5/buildout-cache/eggs/pycountry-20.7.3-py2.7.egg/pycountry/db.py", line 40, in load_if_needed
    self._load()
  File "/home/plone/5/buildout-cache/eggs/pycountry-20.7.3-py2.7.egg/pycountry/db.py", line 67, in _load
    self.data_class_name, (self.data_class_base,), {})
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/plone/5/buildout-cache/eggs/Products.CMFPlone-5.2.2-py2.7.egg/Products/CMFPlone/meta.zcml", line 38.4-42.10
    File "/home/plone/5/zeocluster/parts/client1/etc/site.zcml", line 12.2-12.39
    TypeError: a new-style class can't have only classic bases

**Comment by rnixx** [comment]
> Is there a way to solve this?

Yes, use python 3
