### ISSUE TITLE
<adapter factory=".converter.decimal_converter" /> (Python 3.8.1, Plone 5.2.2 and src/bda.plone.shop, src/bda.plone.cart, etc.)

### ISSUE THREAD

**Issue by registroforzado** [bluedynamics/bda.plone.shop#124]
Is there a way to solve this? Thanks

$ bin/client1 fg
/home/plone/5p381/buildout-cache/eggs/Products.CMFFormController-4.1.2-py3.8.egg/Products/CMFFormController/ControllerPythonScript.py:41: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2020-10-25 00:52:11,126 WARNING [Init:86][MainThread] Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2020-10-25 00:52:11,130 WARNING [Init:86][MainThread] Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
/home/plone/5p381/buildout-cache/eggs/Products.CMFPlacefulWorkflow-2.0.2-py3.8.egg/Products/CMFPlacefulWorkflow/permissions.py:5: DeprecationWarning: setDefaultRoles is deprecated. Please use addPermission from AccessControl.Permission.
  from Products.CMFCore.permissions import setDefaultRoles
/home/plone/5p381/buildout-cache/eggs/Products.PloneHotfix20200121-1.1-py3.8.egg/Products/PloneHotfix20200121/utils.py:4: DeprecationWarning: getSiteEncoding: `getSiteEncoding` is deprecated. Plone only supports UTF-8 currently. This method always returns "utf-8"
  from Products.CMFPlone.utils import *
/home/plone/5p381/buildout-cache/eggs/Products.PortalTransforms-3.1.8-py3.8.egg/Products/PortalTransforms/transforms/text_to_html.py:2: DeprecationWarning: html_quote is deprecated. Please import from DocumentTemplate.html_quote. These shims will go away in DocumentTemplate 4.0.
  from DocumentTemplate.DT_Util import html_quote
2020-10-25 00:52:11,944 WARNING [TemporaryStorage:93][MainThread] DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

/home/plone/5p381/buildout-cache/eggs/tempstorage-5.1-py3.8.egg/tempstorage/TemporaryStorage.py:94: DeprecationWarning: DEPRECATED: Usage of the package tempstorage is deprecated, as it is known to randomly lose data.
Especially on Zope 4. For details see https://github.com/zopefoundation/tempstorage/issues/8
and https://github.com/zopefoundation/tempstorage

  warnings.warn(deprecation_warning, DeprecationWarning)
/home/plone/5p381/buildout-cache/eggs/plone.app.textfield-1.3.4-py3.8.egg/plone/app/textfield/utils.py:10: DeprecationWarning: ComponentLookupError is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ComponentLookupError
/home/plone/5p381/buildout-cache/eggs/yafowil.plone-3.0.0-py3.8.egg/yafowil/plone/connectors.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import MutableMapping as DictMixin
/home/plone/5p381/buildout-cache/eggs/plone.app.upgrade-2.0.34-py3.8.egg/plone/app/upgrade/__init__.py:167: DeprecationWarning: LockItem is deprecated. Please import from OFS.LockItem.
  from webdav.LockItem import LockItem
/home/plone/5p381/buildout-cache/eggs/plone.subrequest-1.9.2-py3.8.egg/plone/subrequest/__init__.py:18: DeprecationWarning: zope.site.hooks has moved to zope.component.hooks. Import of zope.site.hooks will become unsupported in Version 5.0
  from zope.site.hooks import getSite
/home/plone/5p381/buildout-cache/eggs/plone.app.content-3.8.6-py3.8.egg/plone/app/content/browser/vocabulary.py:10: DeprecationWarning: IFieldPermissionChecker is deprecated. Import IFieldPermissionChecker from plone.app.z3cform.interfaces instead
  from plone.app.widgets.interfaces import IFieldPermissionChecker
/home/plone/5p381/buildout-cache/eggs/plone.app.contentrules-4.1.4-py3.8.egg/plone/app/contentrules/actions/logger.py:12: DeprecationWarning: IObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import IObjectEvent
/home/plone/5p381/buildout-cache/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py:241: DeprecationWarning: IComponentRegistry is deprecated. Import from zope.interface.interfaces
  obj = getattr(mod, oname)
/home/plone/5p381/buildout-cache/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py:241: DeprecationWarning: LockableItem is deprecated. Please import from OFS.Lockable.
  obj = getattr(mod, oname)
/home/plone/5p381/buildout-cache/eggs/plone.schemaeditor-3.0.1-py3.8.egg/plone/schemaeditor/utils.py:6: DeprecationWarning: ObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ObjectEvent
/home/plone/5p381/buildout-cache/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py:241: DeprecationWarning: LazyMap is deprecated. Please import from ZTUtils.Lazy.
  obj = getattr(mod, oname)
/home/plone/5p381/buildout-cache/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py:241: DeprecationWarning: LazyCat is deprecated. Please import from ZTUtils.Lazy.
  obj = getattr(mod, oname)
/home/plone/5p381/buildout-cache/eggs/plone.app.upgrade-2.0.34-py3.8.egg/plone/app/upgrade/v50/betas.py:8: DeprecationWarning: ILanguageSchema is deprecated. It has been moved to plone.i18n.interfaces, import from there instead.
  from Products.CMFPlone.interfaces import ILanguageSchema
/home/plone/5p381/buildout-cache/eggs/calmjs.parse-1.2.4-py3.8.egg/calmjs/parse/io.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Iterable
/home/plone/5p381/buildout-cache/eggs/pyScss-1.3.7-py3.8-linux-x86_64.egg/scss/namespace.py:172: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  argspec = inspect.getargspec(function)
/home/plone/5p381/buildout-cache/eggs/pyScss-1.3.7-py3.8-linux-x86_64.egg/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
/home/plone/5p381/buildout-cache/eggs/plone.restapi-6.13.7-py3.8.egg/plone/restapi/serializer/catalog.py:5: DeprecationWarning: Lazy is deprecated. Please import from ZTUtils.Lazy.
  from Products.ZCatalog.Lazy import Lazy
/home/plone/5p381/buildout-cache/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py:241: DeprecationWarning: CartViewlet is deprecated. Import from bda.plone.cart.browser.portlet instead
  obj = getattr(mod, oname)
Traceback (most recent call last):
  File "/home/plone/5p381/zeocluster/parts/client1/bin/interpreter", line 305, in \<module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/Startup/serve.py", line 255, in \<module>
    sys.exit(main() or 0)
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/Startup/serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/plone/5p381/buildout-cache/eggs/PasteDeploy-2.1.0-py3.8.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/plone/5p381/buildout-cache/eggs/PasteDeploy-2.1.0-py3.8.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/home/plone/5p381/buildout-cache/eggs/PasteDeploy-2.1.0-py3.8.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/plone/5p381/buildout-cache/eggs/PasteDeploy-2.1.0-py3.8.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/home/plone/5p381/buildout-cache/eggs/PasteDeploy-2.1.0-py3.8.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/home/plone/5p381/buildout-cache/eggs/PasteDeploy-2.1.0-py3.8.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/plone/5p381/buildout-cache/eggs/PasteDeploy-2.1.0-py3.8.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/Startup/run.py", line 71, in make_wsgi_app
    starter.prepare()
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/Startup/starter.py", line 99, in startZope
    Zope2.startup_wsgi()
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/App/startup.py", line 143, in startup
    load_zcml()
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/App/startup.py", line 58, in load_zcml
    load_site()
  File "/home/plone/5p381/buildout-cache/eggs/Zope-4.5.1-py3.8.egg/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/plone/5p381/buildout-cache/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/xmlconfig.py", line 659, in file
    context.execute_actions()
  File "/home/plone/5p381/buildout-cache/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py", line 784, in execute_actions
    for action in resolveConflicts(self.actions):
  File "/home/plone/5p381/buildout-cache/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py", line 1811, in resolveConflicts
    raise ConfigurationConflictError(conflicts)
zope.configuration.config.ConfigurationConflictError: Conflicting configuration actions
  For: ('adapter', (\<class 'decimal.Decimal'>,), \<InterfaceClass plone.restapi.interfaces.IJsonCompatible>, '')
    File "/home/plone/5p381/buildout-cache/eggs/plone.restapi-6.13.7-py3.8.egg/plone/restapi/serializer/configure.zcml", line 45.4-45.55
          \<adapter factory=".converters.decimal_converter" />
    File "/home/plone/5p381/zeocluster/src/bda.plone.cart/src/bda/plone/cart/restapi/configure.zcml", line 7.2-7.52
        \<adapter factory=".converter.decimal_converter" />

**Comment by registroforzado** [comment]
Sorry, is a bda.plone.cart issue.
